# Copyright 2016-2017 Gorm Andresen (Aarhus University), Jonas Hoersch (FIAS), Tom Brown (FIAS)
# Copyright 2025 Michael Davidson (UCSD), Xiqiang Liu (UCSD)

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


"""Various Preparation Functions for Geodata's modules."""

import calendar
import logging
import os
import shutil
import subprocess
import tempfile
from multiprocessing import Pool
from typing import TYPE_CHECKING

import dask
import numpy as np
import pandas as pd
import xarray as xr

if TYPE_CHECKING:
    from geodata.cutout import Cutout
else:
    Cutout = object

logger = logging.getLogger(__name__)


def cutout_do_task(task: dict, write_to_file: bool = True):
    task = task.copy()
    prepare_func = task.pop("prepare_func")

    if write_to_file:
        datasetfns = task.pop("filenames")

    # Force dask to use just one thread (to save memory)
    with dask.config.set(scheduler="single-threaded"):
        try:
            data = prepare_func(**task)

            if data is None:
                data = []

            if write_to_file:
                for yearmonth, ds in data:
                    if ds is None:
                        continue

                    fn = datasetfns[yearmonth]
                    logger.debug("Writing to %s", os.path.basename(fn))

                    ds.to_netcdf(fn)
                    logger.debug(
                        "Write variable(s) %s to %s generated by %s",
                        ", ".join(ds.data_vars),
                        os.path.basename(fn),
                        prepare_func.__name__,
                    )
                return

            return data

        except Exception as e:
            logger.exception(
                "Exception occured in the task with prepare_func `%s`: %s",
                prepare_func.__name__,
                e.args[0],
            )
            raise e


def cutout_prepare(
    cutout: Cutout,
    overwrite: bool = False,
    nprocesses: int | None = None,
    gebco_height: bool = False,
):
    """Main preparation function for a cutout.

    Args:
        cutout: The cutout object to prepare.
        overwrite: If True, the cutout will be prepared even if it is already prepared.
        nprocesses: Number of processes to use. If None, all processors will be used.
        gebco_height: If True, the function will interpolate the GEBCO bathymetry to the dataset grid.
    """

    if cutout.prepared and not overwrite:
        logger.info(
            "The cutout is already prepared. If you want to recalculate it"
            ", supply an `overwrite=True` argument."
        )
        return True

    if cutout.empty:
        logger.warning(
            "Cutout dimensions are empty. One or more of xs, ys, or time are not "
            "available in Dataset."
        )
        return False

    logger.info("Starting preparation of cutout '%s'", cutout.name)

    cutout_dir = cutout.cutout_dir
    yearmonths = cutout.coords["year-month"].to_index()
    xs = cutout.meta.indexes["x"]
    ys = cutout.meta.indexes["y"]

    if gebco_height:
        logger.info("Interpolating gebco to the dataset grid")
        cutout.meta["height"] = _prepare_gebco_height(xs, ys)

    # Check if cutout_dir exists
    if cutout_dir.is_dir():
        # Delete all files except meta.nc
        for f in cutout_dir.rglob("*.nc"):
            if not f.name.endswith("meta.nc"):
                logger.debug("Deleting %s", f.name)
                f.unlink()
    cutout_dir.mkdir(parents=True, exist_ok=True)

    # Compute data and fill files
    tasks = cutout.dataset_cls.tasks_func(xs=xs, ys=ys, yearmonths=yearmonths)

    for i, t in enumerate(tasks):

        def datasetfn_with_id(ym):
            # returns a filename with incrementing id at end eg `201101-01.nc`
            filename = cutout._get_filename(ym)
            return filename.with_stem(f"{filename.stem}-{i:02d}")

        t["filenames"] = {ym: datasetfn_with_id(ym) for ym in yearmonths.tolist()}

    logger.info(
        "%d tasks have been collected. Starting running them on %s.",
        len(tasks),
        f"{nprocesses} processes" if nprocesses is not None else "all processors",
    )

    with Pool(processes=nprocesses) as pool:
        try:
            pool.map(cutout_do_task, tasks)
        except Exception as e:
            pool.terminate()
            logger.warning(
                "Preparation of cutout '%s' has been interrupted by an exception. "
                "Purging the incomplete cutout_dir.",
                cutout.name,
            )
            shutil.rmtree(cutout_dir)
            raise e

    logger.info("Merging variables into monthly compound files")

    for fn in [cutout._get_filename(ym) for ym in yearmonths.tolist()]:
        # Find all files with yearmonth prefix eg `201101-XX.nc`
        fns = list(cutout_dir.rglob(f"{fn.stem}-*{fn.suffix}"))

        if len(fns) == 1 and not gebco_height:
            # Just a single file. Simply rename
            fns[0].rename(fn)
        else:
            with xr.open_mfdataset(fns, combine="by_coords", chunks="auto") as ds:
                if gebco_height:
                    ds["height"] = cutout.meta["height"]
                ds.to_netcdf(fn)

            for f in fns:
                f.unlink()

        logger.debug("Completed files %s", os.path.basename(fn))

    logger.info("Cutout '%s' has been successfully prepared", cutout.name)
    cutout.prepared = True


def cutout_produce_specific_dataseries(cutout, yearmonth, series_name):
    xs = cutout.coords["x"]
    ys = cutout.coords["y"]
    series = cutout.weather_data_config[series_name].copy()
    series["meta_attrs"] = cutout.meta.attrs
    tasks_func = series["tasks_func"]
    tasks = tasks_func(xs=xs, ys=ys, yearmonths=[yearmonth], **series)

    assert len(tasks) == 1
    data = cutout_do_task(tasks[0], write_to_file=False)
    assert len(data) == 1 and data[0][0] == yearmonth  # type: ignore
    return data[0][1]  # type: ignore


def cutout_get_meta_view(
    cutout: Cutout,
    xs: slice | None = None,
    ys: slice | None = None,
    years=slice(None),
    months=slice(None),
    **dataset_params,
):
    meta = cutout.meta
    meta.attrs["view"] = {}

    if xs is not None:
        meta.attrs["x"] = xs
    if ys is not None:
        meta.attrs["y"] = _prepare_lat_direction(cutout.dataset_cls.lat_direction, ys)

    meta = (
        meta.unstack("year-month")
        .sel(year=years, month=months, **meta.attrs.get("view", {}))
        .stack(dim={"year-month": ("year", "month")})
    )

    meta = meta.sel(
        time=slice(
            *(
                f"{ym[0]:04d}-{ym[1]:02d}"
                for ym in meta["year-month"][[0, -1]].to_index()
            )
        )
    )

    # Check if returned non-zero subset
    # 	Future work: can check if whole subset is available
    dim_len = [len(meta.indexes[i]) for i in meta.indexes]
    if all(d > 0 for d in dim_len):
        return meta

    logger.warning(
        "Certain dimensions are empty with the meta file of the cutout %s", dim_len
    )


def cutout_get_meta(
    cutout: Cutout,
    xs: slice,
    ys: slice,
    years: slice,
    months: slice = slice(1, 12),
    **dataset_params,
) -> xr.Dataset:
    ys = _prepare_lat_direction(cutout.dataset_cls.lat_direction, ys)

    meta_kwds = cutout.meta_data_config.copy()
    meta_kwds.update(dataset_params)

    # Get metadata
    prepare_func: callable = meta_kwds.pop("prepare_func")
    ds: xr.Dataset = prepare_func(
        xs=xs, ys=ys, year=years.stop, month=months.stop, **meta_kwds
    )
    ds.attrs.update(dataset_params)

    # Check if cutout dimenions are empty
    if not np.prod([len(ds.indexes[i]) for i in ds.indexes]):
        logger.warning(
            "Cutout dimensions are empty. "
            "One or more of xs, ys, or time are not available in Dataset."
        )
        cutout.empty = True

    # with metadata, load various parameters
    meta_file_granularity = meta_kwds["file_granularity"]
    month_start = pd.Timestamp(f"{years.stop}-{months.stop}")
    ds.coords["year"] = range(years.start, years.stop + 1)
    ds.coords["month"] = range(months.start, months.stop + 1)

    match meta_file_granularity:
        case "daily":
            start, second, end = map(pd.Timestamp, ds.coords["time"].values[[0, 1, -1]])
            offset_start = start - month_start
            offset_end = end - (month_start + pd.offsets.MonthBegin())
            step = (second - start).components.hours
            ds.coords["time"] = pd.date_range(
                start=pd.Timestamp(f"{years.start}-{months.start}") + offset_start,
                end=(month_start + pd.offsets.MonthBegin() + offset_end),
                freq="h" if step == 1 else f"{step}h",
            )
        case "dailymeans":
            ds.coords["time"] = pd.date_range(
                start=pd.Timestamp(f"{years.start}-{months.start}-1"),
                end=pd.Timestamp(
                    f"{years.stop}-{months.stop}-{calendar.monthrange(years.stop, months.stop)[1]}"
                ),
                freq="d",
            )
        case "monthly":
            ds.coords["time"] = pd.date_range(
                start=pd.Timestamp(f"{years.start}-{months.start}"),
                end=pd.Timestamp(f"{years.stop}-{months.stop}"),
                freq="MS",
            )

    return ds.stack(**{"year-month": ("year", "month")})


def _prepare_gebco_height(xs, ys, gebco_fn=None):
    # gebco bathymetry heights for underwater
    if gebco_fn is None:
        from .config import gebco_path

        gebco_fn = gebco_path

    tmpdir = tempfile.mkdtemp()
    cornersc = np.array(((xs[0], ys[0]), (xs[-1], ys[-1])))
    minc = np.minimum(*cornersc)
    maxc = np.maximum(*cornersc)
    span = (maxc - minc) / (np.asarray((len(xs), len(ys))) - 1)
    minx, miny = minc - span / 2.0
    maxx, maxy = maxc + span / 2.0

    tmpfn = os.path.join(tmpdir, "resampled.nc")
    try:
        ret = subprocess.call(
            [
                "gdalwarp",
                "-of",
                "NETCDF",
                "-ts",
                str(len(xs)),
                str(len(ys)),
                "-te",
                str(minx),
                str(miny),
                str(maxx),
                str(maxy),
                "-r",
                "average",
                gebco_fn,
                tmpfn,
            ]
        )
        assert ret == 0, "gdalwarp was not able to resample gebco"
    except OSError:
        logger.warning(
            "gdalwarp was not found for resampling gebco. "
            "Next-neighbour interpolation will be used instead!"
        )
        tmpfn = gebco_path  # type: ignore

    with xr.open_dataset(tmpfn) as ds_gebco:
        height = (
            ds_gebco.rename({"lon": "x", "lat": "y", "Band1": "height"})
            .reindex(x=xs, y=ys, method="nearest")
            .load()["height"]
        )
    shutil.rmtree(tmpdir)
    return height


def _prepare_lat_direction(lat_direction: bool, ys: slice):
    # Check direction of latitudes encoded in dataset, flip if necessary

    if not lat_direction and ys.stop > ys.start:
        ys = slice(ys.stop, ys.start, -ys.step if ys.step is not None else None)
    if lat_direction and ys.stop < ys.start:
        ys = slice(ys.stop, ys.start, ys.step if ys.step is not None else None)

    return ys
