name: geodata
channels:
  - conda-forge
dependencies:
  - six
  - numpy
  - scipy
  - pandas>=0.22.0
  - xarray>=0.11.2
  - dask>=0.18.0
  - netcdf4
  - progressbar2
  
  # Recommended for pandas and xarray
  - bottleneck
  - numexpr

  # GIS dependencies have to come all from conda-forge
  - conda-forge::pyproj
  - conda-forge::rasterio
  - conda-forge::shapely
  - conda-forge::libgdal
  - conda-forge::geopandas
