name: geodata
channels:
  - conda-forge
dependencies:
  # GIS dependencies have to come all from conda-forge
  - pyproj
  - rasterio
  - shapely
  - libgdal
  - pip
  - pip:
      - six
      - numpy
      - scipy
      - pandas>=0.22.0
      - xarray>=0.11.2
      - dask>=0.18.0
      - netcdf4
      
      # Recommended for pandas and xarray
      - bottleneck
      - numexpr
