# A note on CDS API Key for the ERA5 dataset
# Since CDS API key's format utilizes two lines, it is tricky to write the API key
# secret into the CI runtime.
#
# Thus, we uses a encoding that encodes multi-line strings
# into a single-line string and decodes this encoded string inside the CI runtime.
#
# To replace existing API key secret, encode the CDS API information with base64
# encoding services, such as https://www.base64encode.org/. Use default settings
# when encoding.
#
# Finally, set the secret CDS_API_KEY to the encoded string to complete the process.

name: dev-test

on: [push]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10.15, 3.12.1]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get GDAL for Mac OS
        run: |
          brew install gdal
          pip uninstall -y rasterio
          pip install rasterio
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Configure CDS API Key (Linux/Mac OS)
        run: |
          echo "${{ secrets.CDS_API_KEY }}" | base64 -d > ~/.cdsapirc
          echo "${{ secrets.NETRC_INFO }}" > ~/.netrc
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
      - name: Configure CDS API Key (Windows)
        run: |
          echo "${{ secrets.CDS_API_KEY }}" > $env:USERPROFILE\cdsapi.b64
          certutil -decode $env:USERPROFILE\cdsapi.b64 $env:USERPROFILE\.cdsapirc
          echo "${{ secrets.NETRC_INFO }}" > $env:USERPROFILE\.netrc
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Test with pytest
        run: |
          pip install pytest
          pip install -e ".[download]"
          pytest tests/dev/
